seed: 9061

dataset:
  dat_dir: ???
  resolution: 1
  data_device: cpu
  frameset_type: instant_avatar #imavatar
  num_for_train: -350  # INSTA style split for train/test
  cameras_extent: 1.0

model:
  # (experimental) please set pipe.convert_SHs_python=True if sh_degree>0
  sh_degree: 3 #0
  num_init_samples: 10000
  xyz_as_uvd: True # use _xyz as variables of uvd
  with_mesh_scaling: False  #True
  #max_n_gauss: 300000

pipe:
  convert_SHs_python: False #False
  compute_cov3D_python: False
  debug: False

optim:
  optim_xyz:
    lr: 0.008 #0.005 #0.00016
    scheduler_args:
      lr_init: 0.008 #0.005 #0.00016
      lr_final: 0.0001 #0.00005 #0.0000016
      lr_delay_mult: 0.01
      lr_max_steps: ${optim.total_iteration}
  optim_features:
    lr: 0.0025
  optim_opacity:
    lr: 0.05
  optim_scaling:
    lr: 0.017  #0.005
  optim_rotation:
    lr: 0.001
  optim_deformation:
    lr: 0.0001  #0.0001
    scheduler_args:
      lr_init: 0.0001
      lr_final: 0.0001
      lr_delay_mult: 0.01
      lr_max_steps: ${optim.total_iteration}
  #deform_on : False
  optim_grid:
    lr: 0.005
    scheduler_args:
      lr_init: 0.005
      lr_final: 0.005
      lr_delay_mult: 0.01
      lr_max_steps: ${optim.total_iteration}
  net_lr_step : [5_000, 15_000, 25_000]

  total_iteration: 50000 #300_000 #40_000 #300_000
  first_iter: 1
  save_every_iter: 10000
  testing_iterations: 50000 #300_000  #[ 300_000]

  densify_from_iter: 10_000 #600
  densify_end_iter : 35000
  densification_interval: 500 #100
  densify_until_iter: 300_000 #300_000 #29_000
  opacity_reset_start_iter: 0
  opacity_reset_interval: 5000 #60_000 #60_000
  
  size_threshold: 20
  densify_grad_threshold: 0.0002
  min_opacity: 0.005
  
  lambda_rgb_mse: 10.0
  lambda_ssim: 0.0
  lambda_offset : 1 #10
  lambda_lpips : 0.05
  normal : 0
  lambda_perceptual: 0.01
  lambda_scaling: 1.0  #0.0           # 0.0 for head, 1.0 for instant avatar
  thresh_scaling_max: 0.008
  thresh_scaling_ratio: 10.0
  lambda_sparsity: 0.0
  lambda_dssim : 0.2
  lambda_L1 : 1.5
  metric_xyz: False
  threshold_xyz : 1
  lambda_xyz : 1e-2
  lambda_scale : 1.
  threshold_scale : 0.6
  lambda_dynamic_offset : 0.
  lambda_dynamic_offset_std : 0
  lambda_laplacian : 0.
  metric_scale : False
  background : True
  white_background : True
  # triangle walk
  triangle_walk_interval: 1  #100

  #scheduler:
  #  milestone: 2000
  #  decay: 0.33






